# use an official Python image from Docker Hub 

FROM python:3.10-slim

# Set Working directory inside the container 
WORKDIR /app

# Copy your python code into the container 
COPY app.py .

# Set the default command to run the python app
CMD ["python", "app.py"]
