version: '3.8'
services:
  db:
    image: mysql:8.0
    ports:
      - "3308:3306" # Changed host port to 3308
    environment:
      MYSQL_ROOT_PASSWORD: rootpassword
      MYSQL_DATABASE: todo
      MYSQL_USER: todo
      MYSQL_PASSWORD: todo
    volumes:
      - mysql-data:/var/lib/mysql
  backend:
    build: ./backend
    ports:
      - "5000:5000"
    depends_on:
      - db
    environment:
      DB_HOST: db
      DB_USER: todo
      DB_PASSWORD: todo
      DB_NAME: todo
  frontend:
    build: ./frontend
    ports:
      - "80:80"
    depends_on:
      - backend
    environment:
      REACT_APP_API_URL: http://backend:5000/todos
volumes:
  mysql-data: