version: '3.8'
services:
  db:
    image: postgres:13
    environment:
      POSTGRES_USER: flask_user
      POSTGRES_PASSWORD: flask_password
      POSTGRES_DB: flask_db
    volumes:
      - postgres_data:/var/lib/postgresql/data/

  web:
    build: .
    ports:
      - "5000:5000"
    environment:
      DATABASE_URL: postgresql://flask_user:flask_password@db:5432/flask_db
    depends_on:
      - db

volumes:
  postgres_data: